### ISSUE TITLE
Can you add your demo code to the repo?

### ISSUE THREAD

**Issue by delebash** [colkassad/terrain-rgb-slope#1]
This is exactly what I am looking for.  The way your demo works is the same thing I need for my app.  It would be wonderful if you would share the demo code. TY

**Comment by colkassad** [comment]
Looks like my demo code is using an older version where the slope and height were in one file. I'll sort that out, sanitize some stuff, and post the demo repo as a public project as soon as I can. It's an express map running on Node.js. If you just want to see how to use the code in an express route, this is the code for what happens when the user double clicks a tile and the 16bit PNG is downloaded:

```
var express = require('express');
var router = express.Router();
var fs = require('fs');
var converter = require('terrain-rgb-height');

/* GET elevation. */
router.get('/:zoom/:x/:y/:token', function(req, res) {
    var zoom = req.params.zoom;
    var x = req.params.x;
    var y = req.params.y;
  
    var url = 'https://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}@2x.pngraw?access_token=' + req.params.token;
    url = url.replace('{z}', zoom);
    url = url.replace('{x}', x);
    url = url.replace('{y}', y);
    var inputPng = "./public/images/" + req.params.zoom + "-" + req.params.x + "-" + req.params.y + ".png";
    var outputPng = "./public/images/" + req.params.zoom + "-" + req.params.x + "-" + req.params.y + "-sixteen-bit.png";
    var options = {
      inputFilePath: inputPng,
      outputFilePath: outputPng
    };
	//if the tile was already converted and cached on the server, use that and don't bother converting
    if (fs.existsSync(inputPng)) {
      if (fs.existsSync(outputPng)) {
        res.download(outputPng);
      } else {
        converter.convert(options, function() {
          res.download(outputPng);
        });
      }
    } else {
      converter.getTile(url, inputPng, function() {
        converter.convert(options, function() {
          res.download(outputPng);
        });
      });
    }
  });

module.exports = router;
```
Basically, I created a route that accepts a URL which contains the zoom, x, y, and token (you will need to create a MapBox token if you have not yet), derived from the selected tile in my MapBox map. If that tile has already been selected and converted (I keep them cached on the server using a filename derived from the URL parameters), I serve that to the user. Otherwise I reach out to MapBox, get the tile, and convert/cache it. If you have any questions, let me know. I'll get the repo up as soon as I can.

Glad you find it useful.

**Comment by delebash** [comment]
Thank you very much for the information.  And thanks for getting the demo code up when you have time. Cheers!

**Comment by colkassad** [comment]
No problem I'm closing this issue and using the other one here: https://github.com/colkassad/terrain-rgb-height/issues/5
